<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>RepoMinecraftBridge</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx"><HintPath>$(RepoManaged)/BepInEx/core/BepInEx.dll</HintPath></Reference>
    <Reference Include="UnityEngine"><HintPath>$(RepoManaged)/REPO_Data/Managed/UnityEngine.dll</HintPath></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(RepoManaged)/REPO_Data/Managed/UnityEngine.CoreModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.PhysicsModule"><HintPath>$(RepoManaged)/REPO_Data/Managed/UnityEngine.PhysicsModule.dll</HintPath></Reference>
  </ItemGroup>
</Project>
