// ApiDump - writes a markdown "notes file" for one managed assembly.
//
//   ApiDump <managedDir> <outFile> [assembly.dll] ["kw1;kw2;..."]
//
// Everything is read with System.Reflection.Metadata, so dependencies of the
// dumped assembly are never loaded (a Unity game's Managed folder cannot be
// loaded into a normal AppDomain anyway).

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;
using System.Text;

namespace ApiDump
{
    internal static class Program
    {
        // The five host patch points of the porting guide, in member-name form.
        private const string DefaultGrep =
            "Hurt;Damage;Death;Respawn;Revive;Kill;Input;Move;Movement;Jump;Sprint;Crouch;Sneak;" +
            "Interact;Grab;Cursor;Sensitivity;Camera;ThirdPerson;FieldOfView;Fov;Freeze;Pause;" +
            "Loading;Cutscene;Velocity;Grounded;Kinematic";

        private const string DefaultKeywords =
            "Player;Input;Camera;Controller;Avatar;Health;PhysGrab;Grab;Item;Valuable;Enemy;" +
            "SemiFunc;RunManager;LevelGenerator;Hurt;Damage;Death;Respawn;Chat;Menu;Hud;HUD;" +
            "Cursor;Sensitivity;Interact;ThirdPerson;FieldOfView;Fov";

        private static int Main(string[] args)
        {
            if (args.Length < 2)
            {
                Console.Error.WriteLine("usage: ApiDump <managedDir> <outFile> [assembly.dll] [\"kw1;kw2;...\"] [\"grep1;grep2;...\"] [maxTypes]");
                return 2;
            }

            string managedDir = args[0];
            string outFile = args[1];
            string assemblyFile = args.Length > 2 && args[2].Length > 0 ? args[2] : "Assembly-CSharp.dll";
            // "none" (or an empty argument - Windows PowerShell 5.1 drops empty
            // arguments to native commands, so callers pass "none") means: skip
            // the big type dump and only run the grep.
            string rawKeywords = args.Length > 3 ? args[3] : DefaultKeywords;
            if (rawKeywords == "none")
            {
                rawKeywords = "";
            }
            string[] keywords = rawKeywords
                .Split(new[] { ';', ',' }, StringSplitOptions.RemoveEmptyEntries)
                .Select(k => k.Trim())
                .Where(k => k.Length > 0)
                .ToArray();

            // Grep mode: list only the members whose names match, grouped by pattern.
            // This is the file that actually answers "where do I patch input?".
            // "patchpoints" (or an empty argument) means: search the built-in
            // patch-point list - the five host patch points of the porting guide.
            string rawGrep = args.Length > 4 ? args[4] : null;
            string[] greps;
            if (string.IsNullOrEmpty(rawGrep) || rawGrep == "patchpoints")
            {
                greps = DefaultGrep.Split(';');
            }
            else
            {
                greps = rawGrep
                    .Split(new[] { ';', ',' }, StringSplitOptions.RemoveEmptyEntries)
                    .Select(k => k.Trim())
                    .Where(k => k.Length > 0)
                    .ToArray();
            }

            int maxTypes = 0;
            if (args.Length > 5)
            {
                int.TryParse(args[5], out maxTypes);
            }

            string path = Path.Combine(managedDir, assemblyFile);
            if (!File.Exists(path))
            {
                Console.Error.WriteLine("assembly not found: " + path);
                return 3;
            }

            using (FileStream stream = File.OpenRead(path))
            using (PEReader pe = new PEReader(stream))
            {
                MetadataReader md = pe.GetMetadataReader();
                StringBuilder report = new StringBuilder();
                report.AppendLine("# API notes: " + assemblyFile);
                report.AppendLine();
                report.AppendLine("Generated by `tools/ApiDump` from `" + path + "`.");
                report.AppendLine("Keywords: " + string.Join(", ", keywords));
                report.AppendLine();
                report.AppendLine("Only type names, member names and arities are listed - enough to choose patch");
                report.AppendLine("points, not enough to redistribute game code.");
                report.AppendLine();

                List<TypeDefinitionHandle> handles = md.TypeDefinitions.ToList();
                List<Tuple<string, string>> sections = new List<Tuple<string, string>>();

                foreach (TypeDefinitionHandle handle in handles)
                {
                    TypeDefinition type = md.GetTypeDefinition(handle);
                    string ns = md.GetString(type.Namespace);
                    string name = md.GetString(type.Name);
                    string full = string.IsNullOrEmpty(ns) ? name : ns + "." + name;

                    if (!keywords.Any(k => full.IndexOf(k, StringComparison.OrdinalIgnoreCase) >= 0))
                    {
                        continue;
                    }

                    StringBuilder body = new StringBuilder();
                    body.AppendLine("### " + full);
                    body.AppendLine();
                    body.AppendLine("- base: `" + BaseName(md, type.BaseType) + "`");
                    body.AppendLine("- attributes: " + TypeFlags(type.Attributes));
                    body.AppendLine();

                    List<string> fields = new List<string>();
                    foreach (FieldDefinitionHandle fieldHandle in type.GetFields())
                    {
                        FieldDefinition field = md.GetFieldDefinition(fieldHandle);
                        fields.Add("- " + FieldFlags(field.Attributes) + md.GetString(field.Name));
                    }
                    if (fields.Count > 0)
                    {
                        body.AppendLine("Fields:");
                        body.AppendLine();
                        fields.Sort(StringComparer.Ordinal);
                        foreach (string line in fields)
                        {
                            body.AppendLine(line);
                        }
                        body.AppendLine();
                    }

                    List<string> properties = new List<string>();
                    foreach (PropertyDefinitionHandle propertyHandle in type.GetProperties())
                    {
                        PropertyDefinition property = md.GetPropertyDefinition(propertyHandle);
                        properties.Add("- " + md.GetString(property.Name) + PropertyAccessors(md, property));
                    }
                    if (properties.Count > 0)
                    {
                        body.AppendLine("Properties:");
                        body.AppendLine();
                        properties.Sort(StringComparer.Ordinal);
                        foreach (string line in properties)
                        {
                            body.AppendLine(line);
                        }
                        body.AppendLine();
                    }

                    List<string> methods = new List<string>();
                    foreach (MethodDefinitionHandle methodHandle in type.GetMethods())
                    {
                        MethodDefinition method = md.GetMethodDefinition(methodHandle);
                        string methodName = md.GetString(method.Name);
                        int parameters = method.GetParameters().Count;
                        methods.Add("- " + MethodFlags(method.Attributes) + methodName + "/" + parameters);
                    }
                    if (methods.Count > 0)
                    {
                        body.AppendLine("Methods (name/arity):");
                        body.AppendLine();
                        methods.Sort(StringComparer.Ordinal);
                        foreach (string line in methods)
                        {
                            body.AppendLine(line);
                        }
                        body.AppendLine();
                    }

                    sections.Add(Tuple.Create(full, body.ToString()));
                }

                sections.Sort((a, b) => string.CompareOrdinal(a.Item1, b.Item1));
                report.AppendLine("## Types (" + sections.Count + ")");
                report.AppendLine();
                foreach (Tuple<string, string> section in sections)
                {
                    report.Append(section.Item2);
                }

                if (greps.Length > 0)
                {
                    report.Append("# Patch-point grep");
                    report.AppendLine();
                    report.AppendLine();
                    report.AppendLine("Member names searched: " + string.Join(", ", greps));
                    report.AppendLine();
                    report.AppendLine();
                    foreach (string grep in greps)
                    {
                        report.Append(Grep(md, handles, grep, 40));
                    }
                }

                Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outFile)));
                File.WriteAllText(outFile, report.ToString());
                Console.WriteLine("wrote " + Path.GetFullPath(outFile) + " (" + sections.Count + " types)");
            }

            return 0;
        }

        /// <summary>Lists every type that has a member whose name contains <paramref name="grep"/>.</summary>
        private static string Grep(MetadataReader md, List<TypeDefinitionHandle> handles, string grep, int maxTypes)
        {
            StringBuilder output = new StringBuilder();
            List<Tuple<string, List<string>>> hits = new List<Tuple<string, List<string>>>();

            foreach (TypeDefinitionHandle handle in handles)
            {
                TypeDefinition type = md.GetTypeDefinition(handle);
                string ns = md.GetString(type.Namespace);
                string name = md.GetString(type.Name);
                string full = string.IsNullOrEmpty(ns) ? name : ns + "." + name;

                List<string> members = new List<string>();
                foreach (MethodDefinitionHandle methodHandle in type.GetMethods())
                {
                    MethodDefinition method = md.GetMethodDefinition(methodHandle);
                    string methodName = md.GetString(method.Name);
                    if (methodName.IndexOf(grep, StringComparison.OrdinalIgnoreCase) >= 0)
                    {
                        members.Add("    method " + MethodFlags(method.Attributes) + methodName +
                                    "/" + method.GetParameters().Count);
                    }
                }
                foreach (FieldDefinitionHandle fieldHandle in type.GetFields())
                {
                    FieldDefinition field = md.GetFieldDefinition(fieldHandle);
                    string fieldName = md.GetString(field.Name);
                    if (fieldName.IndexOf(grep, StringComparison.OrdinalIgnoreCase) >= 0)
                    {
                        members.Add("    field  " + FieldFlags(field.Attributes) + fieldName);
                    }
                }
                foreach (PropertyDefinitionHandle propertyHandle in type.GetProperties())
                {
                    PropertyDefinition property = md.GetPropertyDefinition(propertyHandle);
                    string propertyName = md.GetString(property.Name);
                    if (propertyName.IndexOf(grep, StringComparison.OrdinalIgnoreCase) >= 0)
                    {
                        members.Add("    prop   " + propertyName + PropertyAccessors(md, property));
                    }
                }

                if (members.Count > 0)
                {
                    hits.Add(Tuple.Create(full, members));
                }
            }

            hits.Sort((a, b) => string.CompareOrdinal(a.Item1, b.Item1));
            output.AppendLine("## \"" + grep + "\" - " + hits.Count + " types");
            output.AppendLine();
            int shown = maxTypes > 0 ? Math.Min(maxTypes, hits.Count) : hits.Count;
            for (int i = 0; i < shown; i++)
            {
                output.AppendLine("- `" + hits[i].Item1 + "`");
                foreach (string member in hits[i].Item2)
                {
                    output.AppendLine(member);
                }
            }
            if (shown < hits.Count)
            {
                output.AppendLine("- ... " + (hits.Count - shown) + " more types, raise maxTypes to see them");
            }
            output.AppendLine();
            return output.ToString();
        }

        private static string BaseName(MetadataReader md, EntityHandle handle)
        {
            if (handle.IsNil)
            {
                return "-";
            }
            switch (handle.Kind)
            {
                case HandleKind.TypeDefinition:
                {
                    TypeDefinition type = md.GetTypeDefinition((TypeDefinitionHandle)handle);
                    return md.GetString(type.Name);
                }
                case HandleKind.TypeReference:
                {
                    TypeReference reference = md.GetTypeReference((TypeReferenceHandle)handle);
                    return md.GetString(reference.Name);
                }
                default:
                    return handle.Kind.ToString();
            }
        }

        private static string TypeFlags(System.Reflection.TypeAttributes attributes)
        {
            List<string> parts = new List<string>();
            if ((attributes & System.Reflection.TypeAttributes.Public) != 0)
            {
                parts.Add("public");
            }
            if ((attributes & System.Reflection.TypeAttributes.Abstract) != 0)
            {
                parts.Add("abstract");
            }
            if ((attributes & System.Reflection.TypeAttributes.Sealed) != 0)
            {
                parts.Add("sealed");
            }
            return parts.Count > 0 ? string.Join(" ", parts.ToArray()) : "internal";
        }

        private static string FieldFlags(System.Reflection.FieldAttributes attributes)
        {
            string access = (attributes & System.Reflection.FieldAttributes.Public) != 0 ? "public "
                : (attributes & System.Reflection.FieldAttributes.Family) != 0 ? "protected "
                : "private ";
            string statik = (attributes & System.Reflection.FieldAttributes.Static) != 0 ? "static " : "";
            return access + statik;
        }

        private static string MethodFlags(System.Reflection.MethodAttributes attributes)
        {
            string access = (attributes & System.Reflection.MethodAttributes.Public) != 0 ? "public "
                : (attributes & System.Reflection.MethodAttributes.Family) != 0 ? "protected "
                : "private ";
            string statik = (attributes & System.Reflection.MethodAttributes.Static) != 0 ? "static " : "";
            return access + statik;
        }

        private static string PropertyAccessors(MetadataReader md, PropertyDefinition property)
        {
            PropertyAccessors accessors = property.GetAccessors();
            List<string> parts = new List<string>();
            if (!accessors.Getter.IsNil)
            {
                parts.Add("get");
            }
            if (!accessors.Setter.IsNil)
            {
                parts.Add("set");
            }
            return parts.Count > 0 ? " { " + string.Join("; ", parts.ToArray()) + " }" : "";
        }
    }
}
